project_id = "kvhwljmrfnytinkdivtx"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://kvhwljmrfnytinkdivtx.supabase.co"]
jwt_expiry = 3600
enable_signup = true
email_double_confirm_changes = true
enable_anonymous_sign_ins = false

[functions.ai-proxy]
verify_jwt = true

[db]
port = 54322

[storage]
enabled = true
port = 54325
image_transformation = {enabled = true}