// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvhwljmrfnytinkdivtx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2aHdsam1yZm55dGlua2RpdnR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMzIzNzcsImV4cCI6MjA3MzcwODM3N30.zcvC1uxeCWK-X8OZ37Fe8O1tnvrwEnLj58zJ_6N5Nqk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});